name = "skyblocky"
author = "TeamAOF"
version = "1.0.0"

[index]
file = "pack/index.toml"
hash-format = "sha256"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.16"
jumploader-version-id = 3227191
project-id = 0

[options]
no-internal-hashes = true
