name = "Skylore"
author = "Team Aof"
version = "Alpha4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67ebb1f7661f43c848326b6dbfff6ba1f9c93225163ae3ca73d9706d79e07d20"

[versions]
fabric = "0.12.3"
minecraft = "1.17.1"
