name = "Skylore"
author = "Team AoF"
version = "alpha"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4da1e83d4a92d0265669e86cdaac82e7bf80bf3c02de0a26c2d016825130e0d7"

[versions]
fabric = "0.12.2"
minecraft = "1.17.1"
