name = "Skylore"
author = "TeamAOF"
version = "0.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fc5a55de75a22d69d7acc165ad777731881e64f992b8937d7472bc797e74691"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
