# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				item = true
				bee = true
				villager = true
				zombie_villager = true
				cow = true
				skeleton = true
				bat = true
				zombie = true
				armor_stand = true
				glow_item_frame = false
				spider = true
				creeper = true
				player = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				ghoul = true

			[light_sources.settings.entities.bewitchment]
				owl = true

			[light_sources.settings.entities.promenade]
				duck = true

			[light_sources.settings.entities.betteranimalsplus]
				turkey = true
				butterfly = true
				pheasant = true
				badger = true

			[light_sources.settings.entities.adventurez]
				deer = true

			[light_sources.settings.entities.artifacts]
				mimic = true

