[extractinatorConfig]
commonItemChance = 25.0
uncommonItemChance = 12.0
rareItemChance = 6.0
veryRareItemChance = 2.0
extremelyRareItemChance = 1.0
inputCooldown = 8
outputLootMultiplier = 0.1
enableReiPercent = false
maximumUsages = 100
extractinatorRecipe = "MINECRAFT"
[worldConfig]
generateSiltOre_v1 = true
siltVeinSize_v2 = 8
siltVeinsPerChunk_v2 = 9
siltMinSpawnHeight_v1 = -64
siltMaxSpawnHeight_v1 = 24
generateSlushOre_v1 = true
slushVeinSize_v1 = 8
slushVeinsPerChunk_v1 = 10
slushMinSpawnHeight_v1 = 25
slushMaxSpawnHeight_v1 = 48
