hash-format = "sha256"

[[files]]
file = "config/authme.json5"

[[files]]
file = "config/chicken_nerf.json"

[[files]]
file = "config/cleardespawn.json"

[[files]]
file = "config/couplings.json"

[[files]]
file = "config/crimsonmoon.json5"

[[files]]
file = "config/debrand.json"

[[files]]
file = "config/diggusmaximus/blacklist.json5"

[[files]]
file = "config/diggusmaximus/config.json5"

[[files]]
file = "config/diggusmaximus/grouping.json5"

[[files]]
file = "config/fabric/indigo-renderer.properties"

[[files]]
file = "config/inmis.json"

[[files]]
file = "config/libcd.json"

[[files]]
file = "config/libgui.json5"

[[files]]
file = "config/lithium.properties"

[[files]]
file = "config/malilib.json"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/ninjaphenix-container-library.json"

[[files]]
file = "config/okzoomer.json5"

[[files]]
file = "config/plantinajar.json"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/slightguimodifications/config.json5"

[[files]]
file = "config/slightguimodifications/cts.groovy"

[[files]]
file = "config/staff-of-building.json5"

[[files]]
file = "config/structureworld/structures/classic_skyblock.nbt"

[[files]]
file = "config/structureworld/structures/simple_tree.nbt"

[[files]]
file = "config/structureworld/structures/stoneblock.nbt"

[[files]]
file = "config/structureworld/structureworld.json"

[[files]]
file = "config/tweakeroo.json"

[[files]]
file = "config/waila/megane-impl-mixin.json"

[[files]]
file = "config/waila/megane.json"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/wands.json"

[[files]]
file = "config/whereisit.json"

[[files]]
file = "config/winged.json5"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "mods/advancements-enlarger.toml"
metafile = true

[[files]]
file = "mods/amecs.toml"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
metafile = true

[[files]]
file = "mods/auth-me.toml"
metafile = true

[[files]]
file = "mods/building-wands.toml"
metafile = true

[[files]]
file = "mods/can-i-mine-this-block.toml"
metafile = true

[[files]]
file = "mods/chicken-nerf.toml"
metafile = true

[[files]]
file = "mods/cleanview-fabric.toml"
metafile = true

[[files]]
file = "mods/clear-despawn-fabric.toml"
metafile = true

[[files]]
file = "mods/controlling-for-fabric.toml"
metafile = true

[[files]]
file = "mods/couplings-for-fabric-updated.toml"
metafile = true

[[files]]
file = "mods/crimson-moon.toml"
metafile = true

[[files]]
file = "mods/debrand.toml"
metafile = true

[[files]]
file = "mods/diggus-maximus.toml"
metafile = true

[[files]]
file = "mods/expanded-storage-fabric.toml"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
metafile = true

[[files]]
file = "mods/fast-furnace-for-fabric.toml"
metafile = true

[[files]]
file = "mods/harvest-scythes.toml"
metafile = true

[[files]]
file = "mods/improved-stations.toml"
metafile = true

[[files]]
file = "mods/inmis.toml"
metafile = true

[[files]]
file = "mods/libcd.toml"
metafile = true

[[files]]
file = "mods/linked-storage.toml"
metafile = true

[[files]]
file = "mods/lithium.toml"
metafile = true

[[files]]
file = "mods/malilib.toml"
metafile = true

[[files]]
file = "mods/megane.toml"
metafile = true

[[files]]
file = "mods/modmenu.toml"
metafile = true

[[files]]
file = "mods/ok-zoomer.toml"
metafile = true

[[files]]
file = "mods/plant-in-a-jar.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
metafile = true

[[files]]
file = "mods/slotlink.toml"
metafile = true

[[files]]
file = "mods/staff-of-building.toml"
metafile = true

[[files]]
file = "mods/structure-world.toml"
metafile = true

[[files]]
file = "mods/trinkets-fabric.toml"
metafile = true

[[files]]
file = "mods/tweakeroo.toml"
metafile = true

[[files]]
file = "mods/where-is-it.toml"
metafile = true

[[files]]
file = "mods/winged.toml"
metafile = true

[[files]]
file = "mods/wolves-with-armor.toml"
metafile = true

[[files]]
file = "mods/wthit.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.toml"
metafile = true
