name = "AdventureZ"
filename = "adventurez-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3507/306/adventurez-1.4.0.jar"
hash-format = "murmur2"
hash = "4085302173"

[update]
[update.curseforge]
file-id = 3507306
project-id = 390991
