name = "AltLore"
filename = "altlore-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3466/893/altlore-1.0.2.jar"
hash-format = "murmur2"
hash = "3505060108"

[update]
[update.curseforge]
file-id = 3466893
project-id = 527961
release-channel = "beta"
