name = "Annotated DI"
filename = "Annotated-DI-2.0.4+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/528/Annotated-DI-2.0.4+1.17.1.jar"
hash-format = "murmur2"
hash = "1164407871"

[update]
[update.curseforge]
file-id = 3489528
project-id = 501373
