name = "Artifality"
filename = "artifality-0.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3650/925/artifality-0.5.5.jar"
hash-format = "murmur2"
hash = "291425824"

[update]
[update.curseforge]
file-id = 3650925
project-id = 490812
