name = "BackSlot"
filename = "backslot-1.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/151/backslot-1.2.5.jar"
hash-format = "murmur2"
hash = "3729939519"

[update]
[update.curseforge]
file-id = 3645151
project-id = 402739
