name = "BackSlot"
filename = "backslot-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/133/backslot-1.2.2.jar"
hash-format = "murmur2"
hash = "2699085815"

[update]
[update.curseforge]
file-id = 3504133
project-id = 402739
