name = "Besmirchment 2"
filename = "besmirchment-1.18-9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/266/besmirchment-1.18-9.jar"
hash-format = "murmur2"
hash = "4057763848"

[update]
[update.curseforge]
file-id = 3648266
project-id = 542196
