name = "Better Biome Blend"
filename = "betterbiomeblend-1.18.1-1.3.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/207/betterbiomeblend-1.18.1-1.3.2-fabric.jar"
hash-format = "murmur2"
hash = "3164680980"

[update]
[update.curseforge]
file-id = 3615207
project-id = 446253
