name = "Bewitchment"
filename = "bewitchment-1.18-14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3658/194/bewitchment-1.18-14.jar"
hash-format = "murmur2"
hash = "1453608937"

[update]
[update.curseforge]
file-id = 3658194
project-id = 394915
