name = "Biome Makeover"
filename = "biomemakeover-FABRIC-1.18.1-1.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/33/biomemakeover-FABRIC-1.18.1-1.4.3.jar"
hash-format = "murmur2"
hash = "1151318582"

[update]
[update.curseforge]
file-id = 3620033
project-id = 412182
