name = "Cammie's Wearable Backpacks"
filename = "camsbackpacks-2.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/69/camsbackpacks-2.8.jar"
hash-format = "murmur2"
hash = "3740424122"

[update]
[update.curseforge]
file-id = 3625069
project-id = 443091
