name = "Chunky Pregenerator (Fabric)"
filename = "Chunky-1.2.164.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/660/Chunky-1.2.164.jar"
hash-format = "murmur2"
hash = "1504825527"

[update]
[update.curseforge]
file-id = 3579660
project-id = 433175
