name = "Columns"
filename = "columns-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/332/columns-1.3.0.jar"
hash-format = "murmur2"
hash = "853722539"

[update]
[update.curseforge]
file-id = 3667332
project-id = 385230
