name = "Consistency+"
filename = "consistency_plus-0.4.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3510/835/consistency_plus-0.4.1+1.17.jar"
hash-format = "murmur2"
hash = "941139188"

[update]
[update.curseforge]
file-id = 3510835
project-id = 430445
