name = "Consistency+"
filename = "consistency_plus-0.4.1-rc.3+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3494/767/consistency_plus-0.4.1-rc.3+1.17.jar"
hash-format = "murmur2"
hash = "1199367535"

[update]
[update.curseforge]
file-id = 3494767
project-id = 430445
