name = "CraftPresence"
filename = "CraftPresence-Fabric-1.17.1-Release-1.8.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3467/656/CraftPresence-Fabric-1.17.1-Release-1.8.7.jar"
hash-format = "murmur2"
hash = "3169014280"

[update]
[update.curseforge]
file-id = 3467656
project-id = 297038
release-channel = "beta"
