name = "Croptopia's Chocolaterie"
filename = "croptopia-chocolaterie-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/164/croptopia-chocolaterie-1.0.jar"
hash-format = "murmur2"
hash = "358589364"

[update]
[update.curseforge]
file-id = 3652164
project-id = 560262
