name = "Custom Void [Fabric]"
filename = "custom-void-0.4+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3488/238/custom-void-0.4+1.17.jar"
hash-format = "murmur2"
hash = "3192981836"

[update]
[update.curseforge]
file-id = 3488238
project-id = 412621
