name = "Dark Paintings"
filename = "DarkPaintings-Fabric-1.18.1-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3618/369/DarkPaintings-Fabric-1.18.1-9.0.3.jar"
hash-format = "murmur2"
hash = "3024112713"

[update]
[update.curseforge]
file-id = 3618369
project-id = 377281
