name = "Data Attributes"
filename = "dataattributes-1.1.5-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3633/32/dataattributes-1.1.5-1.18.1.jar"
hash-format = "murmur2"
hash = "716086897"

[update]
[update.curseforge]
file-id = 3633032
project-id = 514734
