name = "Dynamic Asset Generator"
filename = "dynamic_asset_generator-fabric-0.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3661/641/dynamic_asset_generator-fabric-0.3.2.jar"
hash-format = "murmur2"
hash = "1983624403"

[update]
[update.curseforge]
file-id = 3661641
project-id = 577096
