name = "Eden Ring"
filename = "eden-ring-0.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/527/eden-ring-0.3.0.jar"
hash-format = "murmur2"
hash = "2138292521"

[update]
[update.curseforge]
file-id = 3636527
project-id = 546590
