name = "Elytra Aeronautics"
filename = "ElytraAeronautics-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/822/ElytraAeronautics-1.0.1.jar"
hash-format = "murmur2"
hash = "2666843365"

[update]
[update.curseforge]
file-id = 3591822
project-id = 563820
