name = "Enchantment Lore"
filename = "enchantment-lore-1.2.4+MC1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3598/915/enchantment-lore-1.2.4+MC1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "2937655320"

[update]
[update.curseforge]
file-id = 3598915
project-id = 430219
