name = "EnvironmentZ"
filename = "environmentz-1.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/187/environmentz-1.1.7.jar"
hash-format = "murmur2"
hash = "2182574346"

[update]
[update.curseforge]
file-id = 3504187
project-id = 410224
