name = "Equipment Compare [Fabric]"
filename = "EquipmentCompare-1.18.1-fabric-1.2.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/493/EquipmentCompare-1.18.1-fabric-1.2.11.jar"
hash-format = "murmur2"
hash = "2878938143"

[update]
[update.curseforge]
file-id = 3595493
project-id = 541329
