name = "Erroring Entity Remover"
filename = "Erroring-Entity-Remover-1.0.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3544/111/Erroring-Entity-Remover-1.0.2+1.18.jar"
hash-format = "murmur2"
hash = "3645034562"

[update]
[update.curseforge]
file-id = 3544111
project-id = 412568
