name = "Erroring Entity Remover"
filename = "Erroring-Entity-Remover-1.0.1+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/895/Erroring-Entity-Remover-1.0.1+1.17.1.jar"
hash-format = "murmur2"
hash = "821143055"

[update]
[update.curseforge]
file-id = 3424895
project-id = 412568
