name = "Exline's Awnings"
filename = "exlineawnings-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/505/exlineawnings-1.18.jar"
hash-format = "murmur2"
hash = "1100978037"

[update]
[update.curseforge]
file-id = 3549505
project-id = 526698
