name = "Exline's Candy Mod"
filename = "candymod-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/467/candymod-1.18.jar"
hash-format = "murmur2"
hash = "1363941165"

[update]
[update.curseforge]
file-id = 3554467
project-id = 521098
