name = "Modular Loot Crates and Bundles"
filename = "lootcrates-2.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3506/482/lootcrates-2.1.1.jar"
hash-format = "murmur2"
hash = "1062722083"

[update]
[update.curseforge]
file-id = 3506482
project-id = 445787
