name = "Modular Loot Crates and Bundles"
filename = "ModularLootcrates-2.7.0-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/836/ModularLootcrates-2.7.0-1.18.1.jar"
hash-format = "murmur2"
hash = "1051515306"

[update]
[update.curseforge]
file-id = 3595836
project-id = 445787
