name = "Farming for Blockheads (Fabric Edition)"
filename = "farmingforblockheads-fabric-1.18.1-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/206/farmingforblockheads-fabric-1.18.1-9.0.3.jar"
hash-format = "murmur2"
hash = "3633775962"

[update]
[update.curseforge]
file-id = 3606206
project-id = 554586
