name = "FibLib"
filename = "FibLib-1.3.0+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3659/506/FibLib-1.3.0+1.18.1.jar"
hash-format = "murmur2"
hash = "2439993884"

[update]
[update.curseforge]
file-id = 3659506
project-id = 582729
