name = "Fireplace Lib"
filename = "Fireplace-Lib-6.3.0+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/440/Fireplace-Lib-6.3.0+1.18.2.jar"
hash-format = "murmur2"
hash = "1030830067"

[update]
[update.curseforge]
file-id = 3669440
project-id = 432845
