name = "Fireplace Lib"
filename = "Fireplace-Lib-6.2.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/314/Fireplace-Lib-6.2.2+1.18.jar"
hash-format = "murmur2"
hash = "2549550552"

[update]
[update.curseforge]
file-id = 3542314
project-id = 432845
