name = "Give Me Hats! [FABRIC]"
filename = "GiveMeHats-1.7.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3556/521/GiveMeHats-1.7.5.jar"
hash-format = "murmur2"
hash = "2819192007"

[update]
[update.curseforge]
file-id = 3556521
project-id = 384009
