name = "Give Me Hats! [FABRIC]"
filename = "GiveMeHats-1.6.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3510/594/GiveMeHats-1.6.6.jar"
hash-format = "murmur2"
hash = "3645434260"

[update]
[update.curseforge]
file-id = 3510594
project-id = 384009
