name = "Harvest Scythes"
filename = "wraith-harvestscythes-2.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3611/454/wraith-harvestscythes-2.4.1.jar"
hash-format = "murmur2"
hash = "752789590"

[update]
[update.curseforge]
file-id = 3611454
project-id = 412225
