name = "HealthCare"
filename = "healthcare-1.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/70/healthcare-1.0.9.jar"
hash-format = "murmur2"
hash = "303419449"

[update]
[update.curseforge]
file-id = 3504070
project-id = 466750
