name = "Immersive Travel Overhaul"
filename = "ITO-1.02.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/48/ITO-1.02.jar"
hash-format = "murmur2"
hash = "1888182034"

[update]
[update.curseforge]
file-id = 3638048
project-id = 460466
