name = "Immortuos Calyx"
filename = "immortuoscalyx-1.2.3-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3642/682/immortuoscalyx-1.2.3-1.18.jar"
hash-format = "murmur2"
hash = "3986532649"

[update]
[update.curseforge]
file-id = 3642682
project-id = 411857
