name = "KubeJS (Fabric)"
filename = "kubejs-fabric-1801.4.3-build.307.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/185/kubejs-fabric-1801.4.3-build.307.jar"
hash-format = "murmur2"
hash = "4106820025"

[update]
[update.curseforge]
file-id = 3666185
project-id = 395864
