name = "LevelZ"
filename = "levelz-1.0.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3508/131/levelz-1.0.14.jar"
hash-format = "murmur2"
hash = "970036807"

[update]
[update.curseforge]
file-id = 3508131
project-id = 517130
