name = "LevelZ"
filename = "levelz-1.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/784/levelz-1.0.13.jar"
hash-format = "murmur2"
hash = "2163440207"

[update]
[update.curseforge]
file-id = 3489784
project-id = 517130
