name = "LevelZ"
filename = "levelz-1.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/65/levelz-1.0.12.jar"
hash-format = "murmur2"
hash = "4194697362"

[update]
[update.curseforge]
file-id = 3482065
project-id = 517130
release-channel = "beta"
