name = "Loading Timer"
filename = "Loading-Timer-1.5.0-Beta1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3369/574/Loading-Timer-1.5.0-Beta1.jar"
hash-format = "murmur2"
hash = "2698377834"

[update]
[update.curseforge]
file-id = 3369574
project-id = 450817
release-channel = "beta"
