name = "Magic Mirror [FABRIC]"
filename = "[1.18+] Magic Mirror 1.3.4b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3634/118/[1.18+] Magic Mirror 1.3.4b.jar"
hash-format = "murmur2"
hash = "4249459632"

[update]
[update.curseforge]
file-id = 3634118
project-id = 401020
