name = "MC Dungeons Weapons"
filename = "mcdw-4.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/276/mcdw-4.0.3.jar"
hash-format = "murmur2"
hash = "991297298"

[update]
[update.curseforge]
file-id = 3622276
project-id = 407311
