name = "MC Dungeons Weapons"
filename = "mcdw-3.5.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3507/540/mcdw-3.5.6.jar"
hash-format = "murmur2"
hash = "3856638800"

[update]
[update.curseforge]
file-id = 3507540
project-id = 407311
