name = "MedievalWeapons"
filename = "medievalweapons-1.1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3644/841/medievalweapons-1.1.8.jar"
hash-format = "murmur2"
hash = "2257746674"

[update]
[update.curseforge]
file-id = 3644841
project-id = 411400
