name = "MedievalWeapons"
filename = "medievalweapons-1.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3460/407/medievalweapons-1.1.7.jar"
hash-format = "murmur2"
hash = "4254422331"

[update]
[update.curseforge]
file-id = 3460407
project-id = 411400
