name = "Mesh"
filename = "Mesh-0.15.0-alpha.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/793/Mesh-0.15.0-alpha.jar"
hash-format = "murmur2"
hash = "2771438744"

[update]
[update.curseforge]
file-id = 3476793
project-id = 320211
release-channel = "beta"
