name = "Mo' Colors"
filename = "mocolors-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/623/mocolors-1.3.0.jar"
hash-format = "murmur2"
hash = "2684486479"

[update]
[update.curseforge]
file-id = 3545623
project-id = 446767
