name = "Modern Beta [Fabric]"
filename = "modern-beta-fabric-2.7+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3501/683/modern-beta-fabric-2.7+1.17.1.jar"
hash-format = "murmur2"
hash = "1929069347"

[update]
[update.curseforge]
file-id = 3501683
project-id = 410423
