name = "MoreBoots Fabric"
filename = "moreboots-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/432/moreboots-2.0.0.jar"
hash-format = "murmur2"
hash = "1761634922"

[update]
[update.curseforge]
file-id = 3550432
project-id = 510884
