name = "MoreBoots Fabric"
filename = "moreboots-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3411/638/moreboots-1.0.0.jar"
hash-format = "murmur2"
hash = "1378312286"

[update]
[update.curseforge]
file-id = 3411638
project-id = 510884
