name = "MoreBoots Fabric"
filename = "moreboots-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3499/988/moreboots-1.1.0.jar"
hash-format = "murmur2"
hash = "2733589046"

[update]
[update.curseforge]
file-id = 3499988
project-id = 510884
