name = "Moss Layers"
filename = "moss-layers-1.18.1-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3594/721/moss-layers-1.18.1-1.0.1.jar"
hash-format = "murmur2"
hash = "3848816558"

[update]
[update.curseforge]
file-id = 3594721
project-id = 563952
