name = "Mystical Index"
filename = "mystical_index-1.18.1-0.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/570/mystical_index-1.18.1-0.0.9.jar"
hash-format = "murmur2"
hash = "2585988140"

[update]
[update.curseforge]
file-id = 3640570
project-id = 567009
