name = "Mythic Mounts"
filename = "mythic-mounts-1.18-5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/886/mythic-mounts-1.18-5.1.jar"
hash-format = "murmur2"
hash = "3871847812"

[update]
[update.curseforge]
file-id = 3666886
project-id = 517650
