name = "Neutral Animals"
filename = "neutral-animals-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/867/neutral-animals-1.2.0.jar"
hash-format = "murmur2"
hash = "2610755069"

[update]
[update.curseforge]
file-id = 3600867
project-id = 486981
