name = "No Hostiles Around Campfire (Fabric)"
filename = "nohostilesaroundcampfire-fabric_1.18.x-3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/181/nohostilesaroundcampfire-fabric_1.18.x-3.8.jar"
hash-format = "murmur2"
hash = "705296936"

[update]
[update.curseforge]
file-id = 3542181
project-id = 539639
