name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh The Biomes You'll Go-fabric-1.18.1-1.3.5.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/168/Oh The Biomes You'll Go-fabric-1.18.1-1.3.5.7.jar"
hash-format = "murmur2"
hash = "3054287835"

[update]
[update.curseforge]
file-id = 3620168
project-id = 391378
