name = "Plushie Mod"
filename = "plushie-mod-1.1-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/945/plushie-mod-1.1-1.18.1.jar"
hash-format = "murmur2"
hash = "672491062"

[update]
[update.curseforge]
file-id = 3559945
project-id = 544197
