name = "Promenade"
filename = "promenade-2.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3633/936/promenade-2.5.1.jar"
hash-format = "murmur2"
hash = "8140919"

[update]
[update.curseforge]
file-id = 3633936
project-id = 399648
