name = "Promenade"
filename = "promenade-2.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/767/promenade-2.5.0.jar"
hash-format = "murmur2"
hash = "2830717282"

[update]
[update.curseforge]
file-id = 3631767
project-id = 399648
