name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-2.3.5+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/505/repurposed_structures_fabric-2.3.5+1.17.1.jar"
hash-format = "murmur2"
hash = "789100875"

[update]
[update.curseforge]
file-id = 3482505
project-id = 391366
release-channel = "beta"
