name = "RPG-Hud [Fabric]"
filename = "[1.17.1][Fabric] RPG-HUD-3.9.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3477/424/[1.17.1][Fabric] RPG-HUD-3.9.1.jar"
hash-format = "murmur2"
hash = "529659812"

[update]
[update.curseforge]
file-id = 3477424
project-id = 397179
release-channel = "beta"
