name = "RpgDifficulty"
filename = "rpgdifficulty-1.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/668/rpgdifficulty-1.0.7.jar"
hash-format = "murmur2"
hash = "2931158310"

[update]
[update.curseforge]
file-id = 3399668
project-id = 480786
release-channel = "beta"
