name = "RpgDifficulty"
filename = "rpgdifficulty-1.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/881/rpgdifficulty-1.0.9.jar"
hash-format = "murmur2"
hash = "358937921"

[update]
[update.curseforge]
file-id = 3615881
project-id = 480786
