name = "ShetiPhianCore [Fabric]"
filename = "shetiphiancore-[fabric]-1.18-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/700/shetiphiancore-[fabric]-1.18-1.2.1.jar"
hash-format = "murmur2"
hash = "1025806603"

[update]
[update.curseforge]
file-id = 3601700
project-id = 536603
