name = "ShetiPhianCore [Fabric]"
filename = "shetiphiancore-[fabric]-1.18-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/776/shetiphiancore-[fabric]-1.18-1.2.2.jar"
hash-format = "murmur2"
hash = "3103884494"

[update]
[update.curseforge]
file-id = 3648776
project-id = 536603
