name = "SkyLib"
filename = "skylorlib-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3656/252/skylorlib-1.2.1.jar"
hash-format = "murmur2"
hash = "849123753"

[update]
[update.curseforge]
file-id = 3656252
project-id = 513100
