name = "Slime Mimic"
filename = "slime-mimic-mod-0.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/511/slime-mimic-mod-0.0.2.jar"
hash-format = "murmur2"
hash = "2966007389"

[update]
[update.curseforge]
file-id = 3599511
project-id = 565905
