name = "Soaring Structures 2 - Clean Version - Forge / Fabric"
filename = "Soaring-Structures-2-1.18.1-2.2-ClearVersion-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/318/Soaring-Structures-2-1.18.1-2.2-ClearVersion-FABRIC.jar"
hash-format = "murmur2"
hash = "1067089879"

[update]
[update.curseforge]
file-id = 3630318
project-id = 573693
