name = "Soaring Structures 2"
filename = "Soaring-Structures-2-1.17.1-1.8.5-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3439/991/Soaring-Structures-2-1.17.1-1.8.5-FABRIC.jar"
hash-format = "murmur2"
hash = "723362319"

[update]
[update.curseforge]
file-id = 3439991
project-id = 496835
