name = "Spice of Fabric (Fabric)"
filename = "spiceoffabric-1.4.1+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/153/spiceoffabric-1.4.1+1.17.1.jar"
hash-format = "murmur2"
hash = "4131754699"

[update]
[update.curseforge]
file-id = 3446153
project-id = 318416
