name = "Spoorn Weapon Attributes"
filename = "spoornweaponattributes-3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/562/spoornweaponattributes-3.2.jar"
hash-format = "murmur2"
hash = "714613743"

[update]
[update.curseforge]
file-id = 3670562
project-id = 573200
