name = "Spoorn Bounty Mobs"
filename = "spoornbountymobs-2.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/720/spoornbountymobs-2.5.2.jar"
hash-format = "murmur2"
hash = "1472189077"

[update]
[update.curseforge]
file-id = 3623720
project-id = 461713
