name = "Spyglass Improvements: Zoom, Quick Access... [Fabric/Forge]"
filename = "spyglass-improvements-1.1+mc1.18.1+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3645/220/spyglass-improvements-1.1+mc1.18.1+fabric.jar"
hash-format = "murmur2"
hash = "1938039211"

[update]
[update.curseforge]
file-id = 3645220
project-id = 571264
