name = "Squirting syringe"
filename = "squirtingsyringe-0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3635/745/squirtingsyringe-0.7.jar"
hash-format = "murmur2"
hash = "686219941"

[update]
[update.curseforge]
file-id = 3635745
project-id = 566397
