name = "Starter Kit (Fabric)"
filename = "starterkit-fabric_1.18.x-3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/112/starterkit-fabric_1.18.x-3.1.jar"
hash-format = "murmur2"
hash = "1670135238"

[update]
[update.curseforge]
file-id = 3542112
project-id = 527822
