name = "Structure Floater Fabric"
filename = "structure_floaters_fabric-2.0.1+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/792/structure_floaters_fabric-2.0.1+1.18.1.jar"
hash-format = "murmur2"
hash = "3732551527"

[update]
[update.curseforge]
file-id = 3570792
project-id = 535399
