name = "Super Cobblestone Funnels"
filename = "SCF118-2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/340/SCF118-2.5.jar"
hash-format = "murmur2"
hash = "2797180765"

[update]
[update.curseforge]
file-id = 3600340
project-id = 398438
