name = "TacoCraft"
filename = "TacoCraft-1.7.2+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/300/TacoCraft-1.7.2+1.18.1.jar"
hash-format = "murmur2"
hash = "1800650869"

[update]
[update.curseforge]
file-id = 3580300
project-id = 373093
