name = "TalkBubbles"
filename = "talkbubbles-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/524/talkbubbles-1.0.1.jar"
hash-format = "murmur2"
hash = "2273785507"

[update]
[update.curseforge]
file-id = 3543524
project-id = 532113
