name = "Taterzens [Fabric]"
filename = "taterzens-1.8.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/133/taterzens-1.8.1-fabric.jar"
hash-format = "murmur2"
hash = "801414437"

[update]
[update.curseforge]
file-id = 3615133
project-id = 446499
