name = "Taterzens [Fabric]"
filename = "taterzens-1.4.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3496/868/taterzens-1.4.2-fabric.jar"
hash-format = "murmur2"
hash = "792962025"

[update]
[update.curseforge]
file-id = 3496868
project-id = 446499
