name = "Terrarian Slimes"
filename = "terrarian-slimes-1.1-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/934/terrarian-slimes-1.1-BETA+1.18.jar"
hash-format = "murmur2"
hash = "1448070471"

[update]
[update.curseforge]
file-id = 3540934
project-id = 465336
