name = "The Extractinator (Fabric)"
filename = "TheExtractinator-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/83/TheExtractinator-1.0.5.jar"
hash-format = "murmur2"
hash = "538836295"

[update]
[update.curseforge]
file-id = 3668083
project-id = 567114
