name = "Things [Fabric]"
filename = "things-0.2.15+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3663/69/things-0.2.15+1.18.jar"
hash-format = "murmur2"
hash = "2093640332"

[update]
[update.curseforge]
file-id = 3663069
project-id = 456151
