name = "TraderNPCs"
filename = "tradernpcs-1.1.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3608/505/tradernpcs-1.1.0-fabric.jar"
hash-format = "murmur2"
hash = "907076439"

[update]
[update.curseforge]
file-id = 3608505
project-id = 550916
