name = "Trap Expansion  (Fabric)"
filename = "trapexpansion-1.3.3+fabric-mc1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/177/trapexpansion-1.3.3+fabric-mc1.18.jar"
hash-format = "murmur2"
hash = "2176949641"

[update]
[update.curseforge]
file-id = 3540177
project-id = 334018
