name = "True Darkness"
filename = "darkness-fabric-mc118-2.0.89.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/757/darkness-fabric-mc118-2.0.89.jar"
hash-format = "murmur2"
hash = "2639782246"

[update]
[update.curseforge]
file-id = 3566757
project-id = 337243
