name = "Unforgiving Void"
filename = "Unforgiving-Void-3.1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/480/Unforgiving-Void-3.1.1+1.18.jar"
hash-format = "murmur2"
hash = "65302385"

[update]
[update.curseforge]
file-id = 3542480
project-id = 274863
