name = "ValleyCraft"
filename = "valley-craft-2.2.2-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/432/valley-craft-2.2.2-1.18.1.jar"
hash-format = "murmur2"
hash = "810123300"

[update]
[update.curseforge]
file-id = 3652432
project-id = 527942
