name = "ValleyCraft"
filename = "valley-craft-2.2.1-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/265/valley-craft-2.2.1-1.18.1.jar"
hash-format = "murmur2"
hash = "4111476645"

[update]
[update.curseforge]
file-id = 3625265
project-id = 527942
