name = "Vein Mining (Fabric)"
filename = "veinmining-fabric-0.0.11-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/270/veinmining-fabric-0.0.11-1.18.jar"
hash-format = "murmur2"
hash = "2340679768"

[update]
[update.curseforge]
file-id = 3546270
project-id = 431910
