name = "VillagerQuests"
filename = "villagerquests-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3497/886/villagerquests-1.0.2.jar"
hash-format = "murmur2"
hash = "2646936946"

[update]
[update.curseforge]
file-id = 3497886
project-id = 534368
