name = "Visuality"
filename = "visuality-mc1.17.1-0.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3457/324/visuality-mc1.17.1-0.1.3.jar"
hash-format = "murmur2"
hash = "1897118515"

[update]
[update.curseforge]
file-id = 3457324
project-id = 521126
release-channel = "beta"
